"""expand dosage form enum

Revision ID: 1c06948fcf0b
Revises: 33840b5f9e84
Create Date: 2026-07-25 17:15:32.499469

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c06948fcf0b"
down_revision: Union[str, Sequence[str], None] = "33840b5f9e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The 8 original members already exist on the live "dosageform" Postgres
# enum type (see b0a8331ddd02); these are the new ones this migration adds.
# SQLAlchemy stores an enum's NAME (not its .value) as the DB-side label.
NEW_DOSAGE_FORMS = [
    "TABLET_CHEWABLE",
    "TABLET_DISPERSIBLE",
    "TABLET_EFFERVESCENT",
    "TABLET_ORODISPERSIBLE",
    "TABLET_ENTERIC_COATED",
    "TABLET_EXTENDED_RELEASE",
    "GRANULES",
    "POWDER_FOR_ORAL_SUSPENSION",
    "LOZENGE",
    "SOLUTION_ORAL",
    "ELIXIR",
    "EMULSION_ORAL",
    "INJECTION_SOLUTION",
    "POWDER_FOR_INJECTION",
    "INFUSION",
    "GEL",
    "LOTION",
    "PASTE",
    "TRANSDERMAL_PATCH",
    "EYE_DROPS",
    "EYE_OINTMENT",
    "EAR_DROPS",
    "NASAL_SPRAY",
    "SUPPOSITORY",
    "PESSARY",
    "ENEMA",
    "INHALER_MDI",
    "INHALER_DPI",
    "NEBULISER_SOLUTION",
]


def upgrade() -> None:
    """Upgrade schema."""
    # WHY guarded by dialect, and why not autogenerated: alembic's
    # autogenerate doesn't detect added Postgres enum labels at all (this
    # was written by hand), and SQLite has no ALTER TYPE / native enum --
    # Base.metadata.create_all() (used everywhere in this project's tests)
    # always reflects the CURRENT Python enum class directly, so SQLite
    # never needs this step; only a real, already-migrated Postgres
    # database has a "dosageform" type frozen at its old 8 values.
    if op.get_bind().dialect.name == "postgresql":
        for name in NEW_DOSAGE_FORMS:
            op.execute(f"ALTER TYPE dosageform ADD VALUE IF NOT EXISTS '{name}'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no ALTER TYPE ... DROP VALUE -- removing an enum label
    # requires rebuilding the type (create new, migrate the column, drop
    # old) even though no row here ever uses the new values yet. Left as a
    # no-op: the extra labels are harmless to leave in place, and the
    # "product" table itself (and its dosage_form column) is fully removed
    # by an earlier migration's downgrade when rolling back past this one.
    pass
