"""P06 validation override

Revision ID: 33840b5f9e84
Revises: bf6ef09c07bf
Create Date: 2026-07-25 16:35:08.983947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "33840b5f9e84"
down_revision: Union[str, Sequence[str], None] = "bf6ef09c07bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_override",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed an op.alter_column('kb_chunk',
    # 'embedding', ...) here -- the same SQLite-reflection false positive
    # noted in prior migrations. Removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validation_override")
    # ### end Alembic commands ###
