"""P03 kb_document and kb_chunk

Revision ID: 761235b82a25
Revises: f7cb45e435e4
Create Date: 2026-07-24 20:57:33.668134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "761235b82a25"
down_revision: Union[str, Sequence[str], None] = "f7cb45e435e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # docker-compose's db image runs scripts/init-pgvector.sql on first boot,
    # but this migration must also work standalone (CI, a fresh non-docker
    # Postgres) — CREATE EXTENSION is idempotent so this is safe either way.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_document",
        sa.Column(
            "source", sa.Enum("ICH", "FDA", "EMA", "WHO", "NAFDAC", name="kbsource"), nullable=False
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=60), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column(
            "license",
            sa.Enum("ICH_HARMONISED", "GOVERNMENT_PUBLIC", "PUBLIC_DOMAIN", name="kblicense"),
            nullable=False,
        ),
        sa.Column("jurisdiction", sa.String(length=60), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kb_chunk",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("section_label", sa.String(length=120), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["kb_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_chunk_document_id"), "kb_chunk", ["document_id"], unique=False)
    # ### end Alembic commands ###

    # Autogenerate has no concept of vector index types, so the HNSW index
    # is added by hand. HNSW over IVFFlat: IVFFlat needs a representative
    # sample already loaded before it clusters well (it's trained via an
    # implicit k-means step), which is awkward for a KB that starts near-
    # empty and grows one document at a time. HNSW builds incrementally with
    # good recall/speed from the first row. cosine distance matches how
    # Voyage (and most text embedding APIs) recommend comparing their
    # vectors — see services/knowledge/retrieve.py.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX ix_kb_chunk_embedding_hnsw ON kb_chunk "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_kb_chunk_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kb_chunk_document_id"), table_name="kb_chunk")
    op.drop_table("kb_chunk")
    op.drop_table("kb_document")
    # ### end Alembic commands ###

    # Same DROP TYPE gap as P01's migration (see its downgrade() comment):
    # Postgres ENUM types outlive DROP TABLE and must be dropped explicitly,
    # or re-running upgrade() after a downgrade() fails with "type already
    # exists". SQLite has no CREATE/DROP TYPE step at all.
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in ("kbsource", "kblicense"):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
