"""certificate and smiles

Revision ID: 76d6a4fb05a9
Revises: 849a57b8a30d
Create Date: 2026-07-25 15:32:46.000356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "76d6a4fb05a9"
down_revision: Union[str, Sequence[str], None] = "849a57b8a30d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "certificate_type",
            sa.Enum("CPP", "GMP", "CEP", "COA", "FREE_SALE", name="certificatetype"),
            nullable=False,
        ),
        sa.Column("issuing_authority", sa.String(length=200), nullable=True),
        sa.Column("certificate_number", sa.String(length=120), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("active_ingredient", sa.Column("smiles", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed an op.alter_column('kb_chunk',
    # 'embedding', ...) here -- the same SQLite-reflection false positive
    # noted in 849a57b8a30d's migration. Removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("active_ingredient", "smiles")
    op.drop_table("certificate")
    # ### end Alembic commands ###
