"""P05 narrative_generation

Revision ID: 849a57b8a30d
Revises: 761235b82a25
Create Date: 2026-07-25 13:55:12.099407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "849a57b8a30d"
down_revision: Union[str, Sequence[str], None] = "761235b82a25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "narrative_generation",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("section_number", sa.String(length=20), nullable=False),
        sa.Column("slot", sa.String(length=60), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("warnings", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "EDITED", name="narrativestatus"),
            nullable=False,
        ),
        sa.Column("final_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "narrative_generation_source",
        sa.Column("narrative_generation_id", sa.Uuid(), nullable=False),
        sa.Column("kb_chunk_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_chunk_id"],
            ["kb_chunk.id"],
        ),
        sa.ForeignKeyConstraint(
            ["narrative_generation_id"],
            ["narrative_generation.id"],
        ),
        sa.PrimaryKeyConstraint("narrative_generation_id", "kb_chunk_id"),
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed an op.alter_column('kb_chunk',
    # 'embedding', ...) here -- a false positive from diffing against a
    # SQLite reflection of the column (which can only see it as NUMERIC,
    # never VECTOR). Removed by hand; the real column type is untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("narrative_generation_source")
    op.drop_table("narrative_generation")
    # ### end Alembic commands ###
