"""P01 full data model

Revision ID: b0a8331ddd02
Revises:
Create Date: 2026-07-11 20:29:51.156499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b0a8331ddd02"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("brand_name", sa.String(length=120), nullable=False),
        sa.Column("generic_name", sa.String(length=200), nullable=False),
        sa.Column("strength_value", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("strength_unit", sa.String(length=20), nullable=True),
        sa.Column(
            "dosage_form",
            sa.Enum(
                "TABLET",
                "CAPSULE_HARD",
                "CAPSULE_SOFT",
                "SYRUP",
                "SUSPENSION",
                "INJECTION",
                "CREAM",
                "OINTMENT",
                name="dosageform",
            ),
            nullable=True,
        ),
        sa.Column("atc_code", sa.String(length=20), nullable=True),
        sa.Column("shelf_life_months", sa.Integer(), nullable=True),
        sa.Column("storage_condition", sa.String(length=300), nullable=True),
        sa.Column("pack_size", sa.String(length=120), nullable=True),
        sa.Column("route_of_administration", sa.String(length=60), nullable=True),
        sa.Column(
            "legal_status",
            sa.Enum(
                "PRESCRIPTION_ONLY",
                "PHARMACY_ONLY",
                "OVER_THE_COUNTER",
                "CONTROLLED_SUBSTANCE",
                name="legalstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "registration_type",
            sa.Enum("NEW", "RENEWAL", "VARIATION", name="registrationtype"),
            nullable=True,
        ),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "batch_formula_line",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("component", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("spec", sa.String(length=40), nullable=False),
        sa.Column("qty_per_unit_mg", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("batch_size_units", sa.Integer(), nullable=False),
        sa.Column("declared_batch_qty_kg", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinical_entry",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("BIOEQUIVALENCE", "LITERATURE", "CLINICAL_STUDY", name="clinicalkind"),
            nullable=False,
        ),
        sa.Column("reference_product", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "excipient",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "function",
            sa.Enum(
                "DILUENT",
                "BINDER",
                "DISINTEGRANT",
                "LUBRICANT",
                "GLIDANT",
                "COATING_AGENT",
                "PRESERVATIVE",
                "SWEETENER",
                "COLORANT",
                "CAPSULE_SHELL",
                name="excipientfunction",
            ),
            nullable=True,
        ),
        sa.Column("grade", sa.String(length=40), nullable=True),
        sa.Column("supplier", sa.String(length=200), nullable=True),
        sa.Column(
            "compendial_status",
            sa.Enum("BP", "USP_NF", "PH_EUR", "JP", "IN_HOUSE", name="compendialstatus"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manufacturer",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "FINISHED_PRODUCT",
                "API_MANUFACTURER",
                "PACKAGING_SITE",
                "CONTRACT_MANUFACTURER",
                name="manufacturerrole",
            ),
            nullable=False,
        ),
        sa.Column("site_address", sa.String(length=300), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column(
            "gmp_status",
            sa.Enum("CERTIFIED", "PENDING", "EXPIRED", "NOT_CERTIFIED", name="gmpstatus"),
            nullable=True,
        ),
        sa.Column("who_gmp", sa.Boolean(), nullable=False),
        sa.Column("pic_s", sa.Boolean(), nullable=False),
        sa.Column("manufacturing_licence", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "packaging",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "component",
            sa.Enum(
                "PRIMARY",
                "SECONDARY",
                "ARTWORK",
                "LABEL",
                "LEAFLET",
                "CARTON",
                name="packagingcomponent",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("material", sa.String(length=120), nullable=True),
        sa.Column("artwork_ref", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("region", sa.Enum("NAFDAC", "FDA", "EU", name="region"), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stability_study",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "study_type",
            sa.Enum("ACCELERATED", "LONG_TERM", "INTERMEDIATE", name="stabilitystudytype"),
            nullable=False,
        ),
        sa.Column("condition", sa.String(length=80), nullable=False),
        sa.Column("duration_months", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "active_ingredient",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=True),
        sa.Column("inn_name", sa.String(length=200), nullable=False),
        sa.Column("salt_form", sa.String(length=200), nullable=True),
        sa.Column("salt_factor", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "compendial_std",
            sa.Enum("BP", "USP_NF", "PH_EUR", "JP", "IN_HOUSE", name="compendialstatus"),
            nullable=True,
        ),
        sa.Column("dmf_number", sa.String(length=80), nullable=True),
        sa.Column("cep_number", sa.String(length=80), nullable=True),
        sa.Column("retest_period_months", sa.Integer(), nullable=True),
        sa.Column("specifications", sa.Text(), nullable=True),
        sa.Column("particle_size", sa.String(length=120), nullable=True),
        sa.Column("residual_solvents", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "section",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("narrative_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sequence",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=4), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence")
    op.drop_table("section")
    op.drop_table("active_ingredient")
    op.drop_table("stability_study")
    op.drop_table("project")
    op.drop_table("packaging")
    op.drop_table("manufacturer")
    op.drop_table("excipient")
    op.drop_table("clinical_entry")
    op.drop_table("batch_formula_line")
    op.drop_table("product")
    # ### end Alembic commands ###
    # Autogenerate doesn't emit these: on Postgres, DROP TABLE does not drop
    # the named ENUM types the columns used, so re-running upgrade() after a
    # downgrade() would fail with "type already exists" without this. SQLite
    # has no CREATE TYPE step (SAEnum compiles to a CHECK constraint there),
    # and DROP TYPE isn't valid SQL there, so only run this on Postgres.
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in (
            "dosageform",
            "legalstatus",
            "registrationtype",
            "clinicalkind",
            "excipientfunction",
            "compendialstatus",
            "manufacturerrole",
            "gmpstatus",
            "packagingcomponent",
            "region",
            "stabilitystudytype",
        ):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
