"""combination product strength move

Revision ID: bf6ef09c07bf
Revises: 76d6a4fb05a9
Create Date: 2026-07-25 16:11:21.765911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bf6ef09c07bf"
down_revision: Union[str, Sequence[str], None] = "76d6a4fb05a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "active_ingredient",
        sa.Column("strength_value", sa.Numeric(precision=10, scale=3), nullable=True),
    )
    op.add_column(
        "active_ingredient", sa.Column("strength_unit", sa.String(length=20), nullable=True)
    )
    # WHY batch mode: SQLite has no ALTER TABLE ADD CONSTRAINT (only
    # add_column works directly) -- batch_alter_table does the
    # copy-and-move workaround SQLite needs, and compiles to a plain ALTER
    # on Postgres. test_migration.py runs this against SQLite, so plain
    # op.create_foreign_key here would pass on Postgres but fail in CI.
    with op.batch_alter_table("batch_formula_line") as batch_op:
        batch_op.add_column(sa.Column("active_ingredient_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_batch_formula_line_active_ingredient_id",
            "active_ingredient",
            ["active_ingredient_id"],
            ["id"],
        )
    op.drop_column("product", "strength_unit")
    op.drop_column("product", "strength_value")
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed an op.alter_column('kb_chunk',
    # 'embedding', ...) here -- the same SQLite-reflection false positive
    # noted in prior migrations. Removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("strength_value", sa.NUMERIC(precision=10, scale=3), nullable=True)
    )
    op.add_column("product", sa.Column("strength_unit", sa.VARCHAR(length=20), nullable=True))
    with op.batch_alter_table("batch_formula_line") as batch_op:
        batch_op.drop_constraint("fk_batch_formula_line_active_ingredient_id", type_="foreignkey")
        batch_op.drop_column("active_ingredient_id")
    op.drop_column("active_ingredient", "strength_unit")
    op.drop_column("active_ingredient", "strength_value")
    # ### end Alembic commands ###
