"""p13 drug substance specification rows

Replaces ActiveIngredient.specifications (free text) with a real
specification table: one row per test, owned by the drug substance. See
app/models/specification.py for why.

DATA NOTE: the old column is dropped without migrating its contents. That
is deliberate and safe here -- the only values that ever existed were seed
strings ("Assay 90.0-120.0%, related substances per BP monograph"), which
the seeds now express as rows. There is no way to parse arbitrary free
text into test/method/criterion triples reliably, and a half-parsed
specification is worse than an absent one: it would look authoritative and
be wrong. If this platform ever holds real applicant data in that column,
this migration needs a hand-written backfill first.

AUTOGENERATE NOTE: `alembic revision --autogenerate` also proposed
DROPping ix_kb_chunk_embedding_hnsw and ix_sequence_leaf_sequence_id_
section_key. Both are real, wanted indexes -- autogenerate simply cannot
round-trip them (the pgvector HNSW index with its operator class, and one
created outside the model metadata), so it reads them as drift and offers
to delete them. Those two lines were removed by hand. Check every
autogenerated migration for this; running it unedited would have silently
dropped the vector index that P03's retrieval depends on.

Revision ID: d2f747481744
Revises: 8434fdfbdb4f
Create Date: 2026-08-14 14:34:10.145116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d2f747481744"
down_revision: Union[str, Sequence[str], None] = "8434fdfbdb4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "specification_test",
        sa.Column("active_ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("test_name", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=200), nullable=False),
        sa.Column("acceptance_criterion", sa.String(length=300), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["active_ingredient_id"], ["active_ingredient.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("active_ingredient", "specifications")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "active_ingredient",
        sa.Column("specifications", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_table("specification_test")
