"""P08 module 1: applicant and declaration

Revision ID: fed49611d433
Revises: 1c06948fcf0b
Create Date: 2026-07-27 11:35:28.510578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fed49611d433"
down_revision: Union[str, Sequence[str], None] = "1c06948fcf0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# New CertificateType members added to the already-live Postgres enum --
# same "ALTER TYPE ADD VALUE, dialect-guarded" pattern as 1c06948fcf0b's
# dosage-form expansion (autogenerate never detects added enum labels;
# SQLite has no native enum type, so Base.metadata.create_all() -- used by
# every test in this project -- always reflects the current Python enum
# directly and never needs this step).
NEW_CERTIFICATE_TYPES = ["TRADEMARK", "MANUFACTURING_LICENCE"]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "applicant",
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_email", sa.String(length=200), nullable=True),
        sa.Column("contact_phone", sa.String(length=60), nullable=True),
        sa.Column("authorized_representative_name", sa.String(length=200), nullable=True),
        sa.Column("authorized_representative_title", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "declaration",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "declaration_type",
            sa.Enum(
                "POWER_OF_ATTORNEY",
                "DECLARATION_OF_AUTHENTICITY",
                "GMP_COMPLIANCE_UNDERTAKING",
                name="declarationtype",
            ),
            nullable=False,
        ),
        sa.Column("signed", sa.Boolean(), nullable=False),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("notarized", sa.Boolean(), nullable=False),
        sa.Column("notarization_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # WHY batch mode: same SQLite "no ALTER TABLE ADD CONSTRAINT" limitation
    # as bf6ef09c07bf's active_ingredient_id FK -- test_migration.py runs
    # this against SQLite, so a bare op.add_column + op.create_foreign_key
    # pair would pass on Postgres but fail in CI.
    with op.batch_alter_table("project") as batch_op:
        batch_op.add_column(sa.Column("applicant_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_project_applicant_id", "applicant", ["applicant_id"], ["id"]
        )

    # WHY guarded by dialect, and why not autogenerated: same rationale as
    # 1c06948fcf0b -- alembic's autogenerate never detects added Postgres
    # enum labels, and SQLite has no ALTER TYPE at all.
    if op.get_bind().dialect.name == "postgresql":
        for name in NEW_CERTIFICATE_TYPES:
            op.execute(f"ALTER TYPE certificatetype ADD VALUE IF NOT EXISTS '{name}'")
    # NOTE: autogenerate also proposed op.alter_column(...) on
    # certificate.certificate_type, kb_chunk.embedding, and
    # product.dosage_form -- the same recurring SQLite-reflection false
    # positive noted in prior migrations (SQLite can only see these as
    # VARCHAR/NUMERIC, never as their real Postgres ENUM/VECTOR types).
    # Removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("project") as batch_op:
        batch_op.drop_constraint("fk_project_applicant_id", type_="foreignkey")
        batch_op.drop_column("applicant_id")
    op.drop_table("declaration")
    op.drop_table("applicant")
    # Postgres enum label removal left as a no-op, same rationale as
    # 1c06948fcf0b -- the extra labels are harmless to leave in place, and
    # Postgres has no ALTER TYPE ... DROP VALUE without a full type rebuild.
