/**
 * Reading a block of tabular data pasted out of a spreadsheet.
 *
 * ## Why this is worth its own module
 *
 * Every stability dataset in existence starts life in Excel. It is
 * generated by a stability chamber's software, tabulated by an analyst,
 * reviewed in a spreadsheet, and only then does anyone think about a
 * dossier. Asking a regulatory affairs officer to retype 5 timepoints
 * across 8 tests -- forty cells, each of which must land against the right
 * limit -- is asking for forty transcription errors and several hours.
 *
 * So the grid accepts a paste. This module is the part that turns the
 * clipboard's text into rows and columns; the grid decides what the
 * columns MEAN. Splitting it that way is what makes the risky half
 * testable without a browser, a component or a fixture.
 *
 * ## What a spreadsheet paste actually looks like
 *
 * Excel, Google Sheets, LibreOffice and Numbers all put TAB-separated
 * text on the clipboard, with rows separated by newlines. That is the
 * format, and it is stable across all four -- which is why this parses
 * text rather than reaching for `text/html` on the clipboard, where the
 * four differ wildly.
 *
 * Three things the naive `split("\n").map(l => l.split("\t"))` gets wrong,
 * and each of them showed up in a real paste:
 *
 *   1. **A cell containing a newline** is quoted, RFC4180-style, so a
 *      line-by-line split tears one row into two.
 *   2. **Windows line endings** leave a trailing `\r` on the last cell of
 *      every row, so "24" becomes "24\r" and never matches anything.
 *   3. **A trailing newline** on the last row, which every spreadsheet
 *      adds, produces a phantom empty row at the bottom.
 *
 * A single-column paste (one value per line, no tabs) is also accepted,
 * because pasting one column of results into one column of the grid is
 * the second most common thing people do.
 */

/** A parsed paste: rows of cells, already trimmed of line-ending noise. */
export type PastedTable = string[][];

/**
 * Split clipboard text into rows and cells.
 *
 * Quoted cells follow the spreadsheet convention: a cell may be wrapped in
 * double quotes, inside which tabs and newlines are literal and `""` means
 * one quote character.
 */
export function parsePastedTable(text: string): PastedTable {
  const rows: PastedTable = [];
  let row: string[] = [];
  let cell = "";
  let quoted = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];

    if (quoted) {
      if (char === '"') {
        // A doubled quote inside a quoted cell is one literal quote --
        // the spreadsheet's own escaping, not the end of the cell.
        if (text[i + 1] === '"') {
          cell += '"';
          i += 1;
        } else {
          quoted = false;
        }
      } else {
        cell += char;
      }
      continue;
    }

    if (char === '"' && cell === "") {
      quoted = true;
    } else if (char === "\t") {
      row.push(cell);
      cell = "";
    } else if (char === "\n") {
      row.push(cell);
      rows.push(row);
      row = [];
      cell = "";
    } else if (char === "\r") {
      // Swallowed rather than kept: a CRLF paste would otherwise leave
      // every row's last cell ending in an invisible character that
      // matches no test name and parses as no number.
      continue;
    } else {
      cell += char;
    }
  }

  if (cell !== "" || row.length > 0) {
    row.push(cell);
    rows.push(row);
  }

  // Drop the phantom trailing row every spreadsheet's final newline
  // produces, and any wholly blank row -- but only blank ones. A row of
  // empty cells in the MIDDLE of a paste is meaningful (a test not
  // performed at any timepoint) and is kept.
  while (rows.length > 0) {
    const last = rows[rows.length - 1];
    if (last.every((value) => value.trim() === "")) rows.pop();
    else break;
  }

  return rows.map((cells) => cells.map((value) => value.trim()));
}

/**
 * A timepoint header cell, as a number of months -- or `null` if the cell
 * does not name one.
 *
 * Real headers are written every way a person might write them: "0", "3",
 * "3 months", "3M", "T3", "6 mo". They are also sometimes not timepoints
 * at all -- the first column of a pasted table is nearly always the test
 * name, and the header above it says "Test" or is empty.
 *
 * Returning `null` rather than guessing is the same discipline the
 * acceptance parser follows: the grid shows the filer which columns it
 * recognised and lets them fix the rest, which is far better than
 * silently filing a column of 12-month data as 0-month data.
 */
export function parseTimepointHeader(cell: string): number | null {
  const match = /(\d+(?:\.\d+)?)/.exec(cell);
  if (!match) return null;
  // Reject a cell whose number is incidental to some other word --
  // "Batch 2" is not a timepoint. Accept a bare number, or a number
  // followed only by a month-ish word.
  if (!/^\s*(?:t|timepoint|month)?\s*\d+(?:\.\d+)?\s*(?:m|mo|mos|month|months)?\s*$/i.test(cell)) {
    return null;
  }
  return Math.round(Number.parseFloat(match[1]));
}

/**
 * Match a pasted row's first cell against the specification's test names.
 *
 * Deliberately forgiving about case, surrounding whitespace and internal
 * spacing, because a spreadsheet's "Related  substances - total" and a
 * specification's "Related substances - total" are the same test and a
 * filer should not have to hunt for the second space. Deliberately NOT
 * forgiving about anything else: a near-miss returns `null` and the row is
 * reported as unmatched, because guessing which test a value answers is
 * guessing which LIMIT it will be judged against.
 */
export function matchTestName<T extends { id: string; test_name: string }>(
  cell: string,
  tests: T[],
): T | null {
  const wanted = normalise(cell);
  if (!wanted) return null;
  return tests.find((test) => normalise(test.test_name) === wanted) ?? null;
}

function normalise(value: string): string {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}

/** One cell the grid understood: a test, a timepoint, and a value. */
export interface MappedCell {
  testId: string;
  timepointMonths: number;
  value: string;
}

export interface PasteMapping {
  cells: MappedCell[];
  /** Timepoint columns recognised, in the order they appeared. */
  timepoints: number[];
  /** Header cells that named no timepoint, and row labels that matched no
   * test. Surfaced to the filer rather than dropped: a paste that half
   * lands is worse than one that visibly did not, because the half that
   * landed looks complete. */
  unmatchedColumns: string[];
  unmatchedRows: string[];
}

/**
 * Map a pasted table onto the specification: first row = timepoints,
 * first column = test names.
 *
 * That orientation is not a guess about the user's spreadsheet -- it is
 * the orientation the grid on screen already uses, and the one every
 * stability report is written in (ICH Q1A(R2)'s own example tables put
 * timepoints across the top). The grid shows it before the paste, so the
 * filer is copying INTO a shape they can see.
 *
 * A cell whose value is empty is skipped rather than recorded as an empty
 * result: a blank in a stability table means "not tested at this
 * timepoint", which the rendered section states in words. Storing "" would
 * make it an empty result, which is a different and worse claim.
 */
export function mapPastedTable<T extends { id: string; test_name: string }>(
  table: PastedTable,
  tests: T[],
): PasteMapping {
  const mapping: PasteMapping = {
    cells: [],
    timepoints: [],
    unmatchedColumns: [],
    unmatchedRows: [],
  };
  if (table.length < 2) return mapping;

  const [header, ...rows] = table;
  // Column index -> timepoint. The first column holds test names, so it is
  // never a timepoint even if its header happens to parse as one.
  const columns = new Map<number, number>();
  header.forEach((cell, index) => {
    if (index === 0) return;
    const months = parseTimepointHeader(cell);
    if (months === null) {
      if (cell.trim()) mapping.unmatchedColumns.push(cell);
      return;
    }
    columns.set(index, months);
  });
  mapping.timepoints = [...columns.values()];

  for (const row of rows) {
    if (row.every((value) => value === "")) continue;
    const test = matchTestName(row[0] ?? "", tests);
    if (test === null) {
      if ((row[0] ?? "").trim()) mapping.unmatchedRows.push(row[0]);
      continue;
    }
    for (const [index, months] of columns) {
      const value = row[index] ?? "";
      if (!value) continue;
      mapping.cells.push({
        testId: test.id,
        timepointMonths: months,
        value,
      });
    }
  }

  return mapping;
}
